# Generated by Django 4.1.4 on 2023-07-11 10:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=125)),
                ('address', models.TextField(default='', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('Other', 'OTHER')], max_length=10)),
                ('position', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=200)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='clients/')),
            ],
        ),
        migrations.CreateModel(
            name='ClientInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('due_date', models.DateField()),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('Paid', 'PAID'), ('Unpaid', 'UNPAID'), ('Partially Paid', 'PARTIALLY PAID')], default='Unpaid', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms_app.client')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(editable=False, max_length=10)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='employees/')),
                ('full_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=125)),
                ('address', models.TextField(default='', max_length=100)),
                ('emergency', models.CharField(max_length=11)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], max_length=10)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('language', models.CharField(choices=[('english', 'ENGLISH'), ('yoruba', 'YORUBA'), ('hausa', 'HAUSA'), ('french', 'FRENCH')], default='english', max_length=10)),
                ('salary', models.CharField(default='00,000.00', max_length=16)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_hours', models.CharField(max_length=5)),
                ('status', models.CharField(choices=[('Pending', 'PENDING'), ('Working', 'WORKING'), ('Completed', 'Completed')], max_length=10, null=True)),
                ('priority', models.CharField(choices=[('Low', 'LOW'), ('Normal', 'NORMAL'), ('High', 'HIGH')], max_length=10)),
                ('cost', models.CharField(max_length=20)),
                ('project_info', models.TextField(max_length=700)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms_app.client')),
                ('team_leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_projects', to='hrms_app.employee')),
                ('team_members', models.ManyToManyField(related_name='assigned_projects', to='hrms_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('status', models.CharField(choices=[('Approved', 'APPROVED'), ('Pending', 'PENDING'), ('Declined', 'DECLINED')], default='Pending', max_length=15)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hrms_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmpBankInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=50)),
                ('branch_code', models.CharField(max_length=10)),
                ('pan_number', models.CharField(max_length=20)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hrms_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('paid_date', models.DateField()),
                ('paid_amount', models.IntegerField()),
                ('payment_method', models.CharField(max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms_app.clientinvoice')),
            ],
        ),
    ]
