# Generated by Django 4.1.4 on 2023-07-12 04:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0003_alter_clientpayment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
