# Generated by Django 4.1.4 on 2023-07-12 05:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0005_remove_employee_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
