# Generated by Django 4.1.4 on 2023-07-12 05:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0007_remove_employee_emergency_remove_employee_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
