# Generated by Django 4.1.4 on 2023-07-12 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0009_alter_employee_gender_emppersonalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='emppersonalinfo',
            name='nationality',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
