# Generated by Django 4.1.4 on 2023-07-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0012_mymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='team_leader',
        ),
        migrations.AddField(
            model_name='project',
            name='team_leader',
            field=models.ManyToManyField(related_name='leading_projects', to='hrms_app.employee'),
        ),
    ]
