# Generated by Django 4.1.4 on 2023-07-13 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0013_remove_project_team_leader_project_team_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leave',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('Approved', 'APPROVED'), ('Pending', 'PENDING'), ('Declined', 'DECLINED'), ('New', 'NEW')], default='Pending', max_length=15),
        ),
    ]
