# Generated by Django 4.1.4 on 2023-07-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0015_alter_leave_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='number_of_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
