# Generated by Django 4.1.4 on 2023-07-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0016_leave_number_of_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='number_of_days',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
