# Generated by Django 4.2.3 on 2023-07-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms_app", "0020_holiday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                choices=[("Male", "MALE"), ("Female", "FEMALE"), ("  Other", "OTHER")],
                max_length=10,
            ),
        ),
    ]
