# Generated by Django 4.2.3 on 2023-07-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms_app", "0021_alter_employee_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave",
            name="status",
            field=models.CharField(
                choices=[
                    ("Approved", "APPROVED"),
                    ("Pending", "PENDING"),
                    ("Declined", "DECLINED"),
                    ("New", "NEW"),
                ],
                default="New",
                max_length=15,
            ),
        ),
    ]
