# Generated by Django 4.2.3 on 2023-07-27 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("hrms_app", "0022_alter_leave_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="mobile",
        ),
        migrations.AddField(
            model_name="employee",
            name="contact",
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employee",
            name="username",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
