# Generated by Django 4.2.3 on 2023-07-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms_app", "0025_employee_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="address",
            field=models.CharField(default="", max_length=100),
        ),
    ]
