# Generated by Django 4.2.3 on 2023-07-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms_app", "0026_alter_employee_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="total_leave_days",
            field=models.IntegerField(default=0),
        ),
    ]
