# Generated by Django 4.2.3 on 2023-07-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms_app", "0027_employee_total_leave_days"),
    ]

    operations = [
        migrations.RenameField(
            model_name="holiday",
            old_name="holiday_date",
            new_name="start_date",
        ),
        migrations.AddField(
            model_name="holiday",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
