# Generated by Django 4.2.3 on 2023-07-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms_app", "0028_rename_holiday_date_holiday_start_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="holiday",
            name="number_of_days",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
