# Generated by Django 4.2.3 on 2023-07-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms_app", "0029_holiday_number_of_days"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MyModel",
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ["date_joined", "full_name"]},
        ),
        migrations.AlterField(
            model_name="employee",
            name="address",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
