# Generated by Django 4.2.3 on 2023-08-01 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hrms_app", "0031_alter_emppersonalinfo_marital_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=50)),
                (
                    "task_status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Pending", "Pending"),
                            ("Working", "Working"),
                            ("Completed", "Completed"),
                        ],
                        default="New",
                        max_length=10,
                    ),
                ),
                (
                    "parent_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="hrms_app.project",
                    ),
                ),
            ],
        ),
    ]
