# Generated by Django 4.2.3 on 2023-08-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms_app", "0032_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
